sonar.projectKey=ChirathiSomadasa_Online-Learning-Platform
sonar.organization=chirathisomadasa
sonar.sources=src
sonar.exclusions=**/node_modules/**,**/tests/**,**/coverage/**
sonar.javascript.lcov.reportPaths=coverage/lcov.info